myWebsite/urls.py
from django.urls import path

from . import views

app_name = 'myWebsite'
urlpatterns = [
    path('', views.home, name='home'),
    path('projects/', views.projects, name='projects'),
    path('coursework/', views.courseWork, name='courseWork'),
    path('contact/', views.contact, name='contact'),
    path('sent/', views.sent, name='sent'),
    path('failed/', views.fail, name='failed'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('myWebsite.urls')),
    path('admin/', admin.site.urls),
]

myWebsite/models.py
from django.db import models

# Create your models here.

myWebsite/views.py
from django.shortcuts import render, redirect, reverse
from django.core.mail import send_mail

def home(request):
    return render(request, 'myWebsite/home.html')

def projects(request):
    return render(request, 'myWebsite/projects.html')

def courseWork(request):
    return render(request, 'myWebsite/courseWork.html')

def contact(request):
    return render(request, 'myWebsite/contact.html')

def sent(request):
    return render(request, 'myWebsite/sent.html')

def fail(request):
    return render(request, 'myWebsite/sent.html')

myWebsite/templates/myWebsite/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">

    <!-- Font Awesome JS -->
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Inconsolata|Oswald|Trade+Winds&display=swap" rel="stylesheet">

</head>

<body>

<div class="wrapper">
    <!-- Sidebar  -->
    <nav id="sidebar">
        <div id="dismiss">
            <i class="fa fa-long-arrow-left fa-lg"></i>
        </div>

        <div class="sidebar-header">
            <h3>Navigation</h3>
        </div>

        <ul class="list-unstyled components">
            <p>Shahroz Imtiaz</p>
            <li>
                <a href="{% url 'myWebsite:home' %}" aria-expanded="false">Home</a>
                <a href="#experienceHeader">Experience</a>
                <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false">Major Projects</a>
                <ul class="collapse list-unstyled" id="pageSubmenu">
                    <li>
                        <a href="#gpiProject">GPI Diagnostics Tool</a>
                    </li>
                    <li>
                        <a href="#cadslist">CADS List</a>
                    </li>
                    <li>
                        <a href="#personalwebsite">Person Website</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#resumeHeader">Resume</a>
            </li>
            <li>
                <a href="#contactForm">Contact</a>
            </li>
        </ul>

        <div class="text-center">
            <a target="_blank" href="https://www.linkedin.com/in/shahroz-imtiaz-30a012126/" class="fa fa-linkedin-square fa-3x" style="padding-right: 1vw"></a>
            <a target="_blank" href="https://github.com/shahrozimtiaz?tab=repositories" class="fa fa-github-square fa-3x"></a>
        </div>
    </nav>

    <!-- Page Content  -->
    <div id="content">

        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow sm-3 mb-5 rounded">
            <div class="container-fluid">

                <button type="button" id="sidebarCollapse" class="btn btn-info" style="background:#7386D5;">
                    <i class="fa fa-th-list"></i>
                    <span>Toggle Sidebar</span>
                </button>


                <div style="font-family: 'Trade Winds', monospace;">
                    <h2>Shahroz Imtiaz</h2>
                </div>
            </div>
        </nav>

        <main role="main" class="container">
            <div class="row">
                <div class="col-md-8">
                    {% block content1 %}{% endblock %}
                </div>
            </div>
        </main>
        {% block content %}{% endblock %}
        <!-- Footer -->

    <!-- Copyright -->
    <!--<div class="footer-copyright text-center py-3">© 2019 Copyright:-->
        <!--<a href="{% url 'myWebsite:home' %}"> Shahroz Imtiaz</a>-->
    <!--</div>-->
    <!-- Copyright -->

<!-- Footer -->
    </div>

    <div class="overlay"></div>

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#sidebar").mCustomScrollbar({
                theme: "minimal"
            });

            $('#dismiss, .overlay').on('click', function () {
                $('#sidebar').removeClass('active');
                $('.overlay').removeClass('active');
            });

            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').addClass('active');
                $('.overlay').addClass('active');
                $('.collapse.in').toggleClass('in');
                $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            });
        });
    </script>
</div>
</body>

<!--<nav class="navbar navbar-expand-lg navbar-dark bg-dark">-->
<!--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">-->
<!--<span class="navbar-toggler-icon"></span>-->
<!--</button>-->
<!--<div class="collapse navbar-collapse" id="navbarTogglerDemo01">-->
<!--<a class="navbar-brand" href="{% url 'myWebsite:home' %}"> <i class="fa fa-home"></i> Shahroz Imtiaz</a>-->
<!--<ul class="navbar-nav mr-auto mt-2 mt-lg-0">-->
<!--<li class="nav-item active">-->
<!--<a class="nav-link" href="{% url 'myWebsite:projects' %}"> <i class="fa fa-database"></i> Projects<span class="sr-only">(current)</span></a>-->
<!--</li>-->
<!--<li class="nav-item active">-->
<!--<a class="nav-link" href="{% url 'myWebsite:courseWork' %}"><i class="fa fa-university"></i> Course Work</a>-->
<!--</li>-->
<!--<li class="nav-item active">-->
<!--<a class="nav-link" href="{% url 'myWebsite:contact' %}"><i class="fa fa-comments"></i> Contact</a>-->
<!--</li>-->
<!--</ul>-->
<!--<form class="form-inline my-2 my-lg-0">-->
<!--<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
<!--<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--</form>-->
<!--</div>-->
<!--</nav>-->

<style>

@import "https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700";

body {
    font-family: 'Poppins', sans-serif;
    background: #f7f7f7;
}

p {
    font-family: 'Poppins', sans-serif;
    font-size: 1.1em;
    line-height: 1.7em;
    color: #999;
}

a,
a:hover,
a:focus {
    color: inherit;
    text-decoration: none;
    transition: all 0.3s;
}

.navbar {
    padding: 15px 10px;
    background: #fff;
    border: none;
    border-radius: 0;
    margin-bottom: 40px;
}

.navbar-btn {
    box-shadow: none;
    outline: none !important;
    border: none;
}

.line {
    width: 100%;
    height: 1px;
    border-bottom: 1px dashed #ddd;
    margin: 40px 0;
}

/* ---------------------------------------------------
    SIDEBAR STYLE
----------------------------------------------------- */

#sidebar {
    width: 250px;
    position: fixed;
    top: 0;
    left: -250px;
    height: 100vh;
    z-index: 999;
    background: #7386D5;
    color: #fff;
    transition: all 0.3s;
    overflow-y: scroll;
    box-shadow: 3px 3px 3px rgba(0, 0, 0, 0.2);
}

#sidebar.active {
    left: 0;
}

#dismiss {
    width: 35px;
    height: 35px;
    line-height: 35px;
    text-align: center;
    background: #7386D5;
    position: absolute;
    top: 10px;
    right: 10px;
    cursor: pointer;
    -webkit-transition: all 0.3s;
    -o-transition: all 0.3s;
    transition: all 0.3s;
}

#dismiss:hover {
    background: #fff;
    color: #7386D5;
}

.overlay {
    display: none;
    position: fixed;
    width: 100vw;
    height: 100vh;
    background: rgba(0, 0, 0, 0.7);
    z-index: 998;
    opacity: 0;
    transition: all 0.5s ease-in-out;
}
.overlay.active {
    display: block;
    opacity: 1;
}

#sidebar .sidebar-header {
    padding: 20px;
    background: #6d7fcc;
}

#sidebar ul.components {
    padding: 20px 0;
    border-bottom: 1px solid #47748b;
}

#sidebar ul p {
    color: #fff;
    padding: 10px;
}

#sidebar ul li a {
    padding: 10px;
    font-size: 1.1em;
    display: block;
}

#sidebar ul li a:hover {
    color: #7386D5;
    background: #fff;
}

#sidebar ul li.active>a,
a[aria-expanded="true"] {
    color: #fff;
    background: #6d7fcc;
}

a[data-toggle="collapse"] {
    position: relative;
}

.dropdown-toggle::after {
    display: block;
    position: absolute;
    top: 50%;
    right: 20px;
    transform: translateY(-50%);
}

ul ul a {
    font-size: 0.9em !important;
    padding-left: 30px !important;
    background: #6d7fcc;
}

ul.CTAs {
    padding: 20px;
}

ul.CTAs a {
    text-align: center;
    font-size: 0.9em !important;
    display: block;
    border-radius: 5px;
    margin-bottom: 5px;
}

a.article,
a.article:hover {
    background: #6d7fcc !important;
    color: #fff !important;
}

/* ---------------------------------------------------
    CONTENT STYLE
----------------------------------------------------- */

#content {
    width: 100%;
    padding: 20px;
    min-height: 100vh;
    transition: all 0.3s;
    position: absolute;
    top: 0;
    right: 0;
}
</style>



</html>

myWebsite/templates/myWebsite/contact.html
{% extends "myWebsite/base.html" %}
{% load staticfiles %}

{% block content %}
<main role="main" class="container" style=" margin: 0 auto; padding-top:15px">
    <div class="row shadow p-3 mb-5 rounded" style=" margin: 0 auto;background:rgb(249, 250, 248);">
        <div class="col-md-8" style=" margin: 0 auto;">
            <!--Section: Contact v.2-->
            <section class="mb-4" style=" margin: 0 auto;">

                <!--Section heading-->
                <h2 class="h1-responsive font-weight-bold text-center my-4">Contact Me</h2>
                <!--Section description-->
                <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact me.</p>

                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-9 mb-md-0 mb-5">
                        <form id="contact-form" name="contact-form" method="POST">
                            {% csrf_token %}

                            <!--Grid row-->
                            <div class="row">

                                <!--Grid column-->
                                <div class="col-md-6">
                                    <div class="md-form mb-0">
                                        <input type="text" id="name" name="name" class="form-control" placeholder="Your name" required />
                                    </div>
                                </div>
                                <!--Grid column-->

                                <!--Grid column-->
                                <div class="col-md-6">
                                    <div class="md-form mb-0">
                                        <input type="text" id="email" name="email" class="form-control" placeholder="Your email" required />
                                    </div>
                                </div>
                                <!--Grid column-->

                            </div><br>
                            <!--Grid row-->

                            <!--Grid row-->
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="md-form mb-0">
                                        <input type="text" id="subject" name="subject" class="form-control" placeholder="Subject" required />
                                    </div>
                                </div>
                            </div><br>
                            <!--Grid row-->

                            <!--Grid row-->
                            <div class="row">

                                <!--Grid column-->
                                <div class="col-md-12">

                                    <div class="md-form">
                                        <textarea type="text" id="message" name="message" rows="4" class="form-control md-textarea" placeholder="Your Message" required></textarea>
                                    </div>

                                </div>
                            </div><br>
                            <!--Grid row-->
                            <div class="text-center text-md-center" style="padding-bottom:15px;">
                                <input class="btn btn-primary" type="submit" value="Send">
                            </div>

                        </form>


                        <div class="status"></div>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-md-3 text-center">
                        <ul class="list-unstyled mb-0">
                            <li><i class="fa fa-map-marker fa-2x"></i>
                                <p>Leesburg, VA</p>
                            </li>

                            <li><i class="fa fa-phone fa-2x"></i>
                                <p>571-420-5607</p>
                            </li>

                            <li><i class="fa fa-envelope fa-2x"></i>
                                <p>shahrozimtiaz07@gmail.com</p>
                            </li>
                        </ul>
                    </div>
                    <!--Grid column-->

                </div>

            </section>
        </div>
    </div>
</main>
<!--Section: Contact v.2-->
{% endblock %}

myWebsite/templates/myWebsite/courseWork.html
{% extends "myWebsite/base.html" %}

myWebsite/templates/myWebsite/failed.html
{% extends "myWebsite/base.html" %}
{% load staticfiles %}

{% block content %}

<div class="card shadow p-3 mb-5 rounded" style="max-width: 18rem; margin:auto;">
  <div class="card-body">
    <h5 class="card-title">Apologizes!</h5>
    <p class="card-text">Something went wrong. Please email me your message, which I've put at the bottom for convenience!</p>
    <a href="{% url 'myWebsite:home' %}" class="btn btn-primary">Home</a>
  </div>
</div>
<h3>Message: <h5></h5></h3>

{% endblock %}

myWebsite/templates/myWebsite/home.html
{% extends "myWebsite/base.html" %}
{% load staticfiles %}

{% block content %}
<div class="text-center" id="profilePicture">
    <a href="https://imgbb.com/"><img src="https://i.ibb.co/GWv9Ns5/circle-selfie.png" alt="circle-selfie" border="0" height="300vw" width="300vw"></a>
</div>

<br>
<div class="text-center" style="width:60vw; margin:auto; font-family: 'Inconsolata', monospace; overflow:visible">
    <h4>
        Hi! My name is Shahroz Imtiaz and I'm a 4th year at the University of Virginia.
        This website was designed and built by me to showcase my work experience, projects, and resume, as well as, provide
        an easy way to contact me!
    </h4>
</div>
<div class="wrapper" style="font-family: 'Inconsolata', monospace;">
    <h2 id="experienceHeader" style="padding:8vw 0 0 13vw">Experience</h2>
        <div class="row" style="padding:3vw 0 0 17vw;">
            <div class="col-sm-3">
            <div class="card" style="width: 18rem; height: 35rem;">
                <img class="card-img-top" src="https://i.ibb.co/J3y6Hh5/swifty.jpg" alt="No Image" height="163vw">
                <div class="card-body">
                    <h5 class="card-title font-weight-bold">SWIFT</h5>
                    <p class="card-text">
                        Interned on the Global Payments Innovation (GPI) team at SWIFT (the
                        global provider of secure financial messaging services) developing a
                        diagnostics utility to add a business context to SWIFT’s databases as well
                        as provide useful tools for the GPI developers.
                    </p>
                </div>
            </div>
            </div>
            <div class="col-sm-3">
            <div class="card" style="width: 18rem; height: 35rem;">
                <img class="card-img-top" src="https://i.ibb.co/09v0gks/uva-rotunda-sunset-sanjay-suchak.jpg" alt="No Image" height="163vw">
                <div class="card-body">
                    <h5 class="card-title font-weight-bold">CS 2501: TEACHING ASSISTANT</h5>
                    <p class="card-text">
                        TA for Software Development Essentials (SDE) at the University of
                        Virginia. Helped students not only understand higher level programming
                        concepts, but also the Software Development process and principles.
                    </p>
                </div>
            </div>
            </div>
            <div class="col-sm-3">
            <div class="card" style="width: 18rem; height: 35rem;">
                <img class="card-img-top" src="https://i.ibb.co/894thJ3/5471f001af3d5ff214b96bca2248add7.jpg" alt="No Image" height="163vw">
                <div class="card-body">
                    <h5 class="card-title">LOUDOUN COUNTY RUST LIBRARY: IT DEPARTMENT</h5>
                    <p class="card-text">
                        Assisted People in resolving their technological issues (software and hardware) and taught on how to optimally use technology.
                    </p>
                </div>
            </div>
            </div>
    </div>
    <h2 style="padding:4vw 0 0 13vw">Major Projects</h2>
    <ul class="list-unstyled mb-0">
        <li>
            <h4 id="gpiProject" style="padding:3vw 0 0 17vw">- GPI Diagnostics Utility</h4>
            <p style="padding:2vw 0 0 21vw">Spent 10 weeks developinga usefuldiagnosticstool using Java back-end,
                Angular front-end, and tyingthem together using a REST API. This tool helped developers at my company do what wasn’t
                possible before and improve on the efficiency of what was possible before resulting in the employeessaving
                time and the company saving money.
            </p>
        </li>
        <li>
            <h4 id="cadslist" style="padding:3vw 0 0 17vw">- CADS List</h4>
            <p style="padding:2vw 0 0 21vw">Spent 10 weeks developinga usefuldiagnosticstool using Java back-end,
                Spent one semester with my team developing an online marketplace to
                buy and sell items within the UVA community using Python, Django,
                PostgreSQL, Bootstrap, Heroku, and TravisCI.
            </p>
        </li>
        <li>
            <h4 id="personalwebsite" style="padding:3vw 0 0 17vw">- Personal Website Using HTML, JavaScript, and CSS</h4>
            <p style="padding:2vw 0 0 21vw">Check it out: https://shahrozimtiaz.github.io./
                The website presents a user-friendly version of my GitHub page.
                Numerous other projects I’ve worked on can easily be found on the site.
                The password is: p1
            </p>
        <li>

            <h4 style="padding:3vw 0 0 17vw">- Automation</h4>
            <p style="padding:2vw 0 0 21vw"> Used Python scripting for home automation such as weather alerts and
                web-scraping.
            </p>
        </li>

        <li>
            <h4 style="padding:3vw 0 0 17vw">- Machine Learning Classifier:</h4>
            <p style="padding:2vw 0 0 21vw"> Built a classifier that was able to identify if a person had chronic kidney
                disease given some useful details. The classifier was accurate 83% of the
                time.
            </p>
        </li>

        <li>

            <h4 style="padding:3vw 0 0 17vw">- Real Estate Agent</h4>

            <p style="padding:2vw 0 0 21vw">Created Java interactive program that allows user to search for available
                houses that meet their specified criteria (distance, location, style of
                home, number of bedroom/bathrooms, etc.)
            </p>
        </li>

        <li>

            <h4 style="padding:3vw 0 0 17vw">- Hoohacks Hero</h4>

            <p style="padding:2vw 0 0 21vw">Worked with a group of 5 to develop a UVA CS courses simulator using
                HTML and JavaScript during a UVA sponsored hackathon.
            </p>
        </li>

        <li>

            <h4 style="padding:3vw 0 0 17vw">- Game Development</h4>
            <p style="padding:2vw 0 0 21vw">I spend a lot of my free time developing videogames to further my skills.
                I’ve developed several games using HTML and JavaScript, Python, Java,
                and Unreal Engine.
            </p>
        </li>
    </ul>
    <h2 style="padding:4vw 0 2vw 13vw">Resume</h2>
</div>
<div class="text-center">
    <iframe id="resumeHeader" src="https://docdro.id/6oRQEYG" height="830vw" width="800vw"></iframe>
</div>
<main role="main" id="contactForm" class="container" style=" margin: 0 auto; padding-top:3vw">
    <div class="row shadow p-3 mb-5 rounded" style=" margin: 0 auto;background:rgb(249, 250, 248);">
        <div class="col-md-8" style=" margin: 0 auto;">
            <!--Section: Contact v.2-->
            <div class="text-center" style=" margin: 0 auto;">

                <!--Section heading-->
                <h2 class="h1-responsive font-weight-bold text-center my-4">Contact Me</h2>
                <!--Section description-->
                <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact me.</p>

                <div class="mb-0">
                    <i class="fa fa-map-marker fa-2x"></i>
                    <p>Leesburg, VA</p>


                    <a class="fa fa-phone fa-2x" href="tel:5714205607?" target="_top"></a>
                    <p>571-420-5607</p>

                    <a class="fa fa-envelope fa-2x" href="mailto:shahrozimtiaz07@gmail.com?" target="_top"></a>
                    <p>shahrozimtiaz07@gmail.com</p>
                    <div class="text-center">
                        <a target="_blank" href="https://www.linkedin.com/in/shahroz-imtiaz-30a012126/" class="fa fa-linkedin-square fa-3x" style="padding-right: 1vw"></a>
                        <a target="_blank" href="https://github.com/shahrozimtiaz?tab=repositories" class="fa fa-github-square fa-3x"></a>
                    </div>
                </div>
                <!--Grid column-->


            </div>
        </div>
    </div>
</main>
{% endblock %}

myWebsite/templates/myWebsite/projects.html
{% extends "myWebsite/base.html" %}

myWebsite/templates/myWebsite/sent.html
{% extends "myWebsite/base.html" %}
{% load staticfiles %}

{% block content %}

<div class="card shadow p-3 mb-5 rounded" style="max-width: 18rem; margin:auto;">
  <div class="card-body">
    <h5 class="card-title">Thank You!</h5>
    <p class="card-text">Your message has been sent!</p>
    <a href="{% url 'myWebsite:home' %}" class="btn btn-primary">Home</a>
  </div>
</div>

{% endblock %}